GET https://app.spyteam.fr:8000/User/Getuser/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyaW5vQGdtYWlsLmNvbSIsImhhc2hlZF9wYXNzd29yZCI6IiQyYiQxMiRuczdEZGdkYy9semRFYk9MQWJFLy9lelZSc0doei9wMnNrSXJFVGNiUE1HMEJmSkhvS3FSNiIsImV4cCI6MTcxOTI3NDE5OX0.-ASuE_BWQuU3944t8W2gOcvDXO_QqEwgRhMZ0doYXYY